insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Blueberries - Frozen', 82.37, 2, 1, 2, 6);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Otomegusa Dashi Konbu', 4.08, 1, 8, 13, 14);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Sugar - Icing', 55.97, 3, 1, 4, 5);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Tart Shells - Sweet, 2', 25.32, 1, 1, 10, 8);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Cherries - Maraschino,jar', 31.15, 1, 5, 5, 20);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Nectarines', 94.78, 5, 7, 13, 11);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Salad Dressing', 58.36, 3, 4, 13, 4);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Fudge - Cream Fudge', 84.18, 2, 4, 4, 2);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Irish Cream - Butterscotch', 47.54, 4, 6, 5, 8);
insert into products (name, price, category_id, brand_id, added_by_employee_id, updated_by_employee_id) values ('Pasta - Orecchiette', 22.94, 1, 4, 9, 1);
